# Generated by Django 5.1 on 2024-08-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('genre', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('review_text', models.TextField()),
                ('reviewer_name', models.CharField(max_length=100)),
                ('review_date', models.DateTimeField()),
            ],
        ),
    ]
