# Generated by Django 5.1 on 2024-08-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviereview',
            name='review_date',
        ),
        migrations.AlterField(
            model_name='moviereview',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='moviereview',
            name='reviewer_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='moviereview',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
